### ISSUE TITLE
Does relish support hapi v17?

### ISSUE THREAD

**Issue by csakis** [dialexa/relish#18]

**Comment by galenandrew** [comment]
@csakis, thanks for the question! Relish does not support Hapi 17 at the moment due to changes in the [lifecycle methods](https://hapijs.com/api#lifecycle-methods) signature (i.e. the `failAction` function in Relish).

I have started working updating Relish to support Hapi v17, however I don't have an exact ETA for when it will be ready. I will make sure to update this issue when it does ship.

**Comment by johannessjoberg** [comment]
Any news on this? :)

**Comment by galenandrew** [comment]
Thank you all for your patience here! Relish@3.0.0 now supports Hapi v17.
